// src/data/calculators/roas.ts
export const roasCalculatorContent = {
  meta: {
    seoTitle: "ROAS Calculator - Return on Ad Spend Calculator (Free)",
    metaDescription: "Calculate ROAS (Return on Ad Spend) free & instant from ad revenue and ad cost. Includes campaign profit, break-even ROAS and good ROAS benchmarks.",
    canonicalSlug: "/roas-calculator",
    ogTitle: "ROAS Calculator - Return on Ad Spend",
    ogDescription: "Instantly calculate Return on Ad Spend (ROAS) and campaign profit.",
    twitterTitle: "Free ROAS Calculator - Return on Ad Spend",
    twitterDescription: "Calculate Return on Ad Spend instantly, free and accurate.",
  },

  hero: {
    text: "The ROAS Calculator instantly finds your Return on Ad Spend and campaign profit from ad revenue and ad spend. Use it to evaluate campaign performance, compare channels, or decide whether to scale or pause a campaign. Anyone running paid ads on Google, Meta, TikTok or any platform can use this free tool.",
  },

  about: {
    text: `The ROAS Calculator is a free online tool that computes Return on Ad Spend (ROAS) and campaign profit from the revenue generated by an ad campaign and its total ad spend.

ROAS is one of the most widely used metrics in digital advertising — it shows how much revenue was generated for every dollar spent on ads, making it easy to compare campaigns, channels, or time periods.

It's useful for marketers evaluating campaign performance, agencies reporting to clients, and business owners deciding where to allocate ad budget.

ROAS differs from ROI: ROAS compares revenue to ad spend only, while ROI (Return on Investment) typically factors in product cost and other expenses to measure true profitability, not just revenue generated.

Limitations: this tool measures revenue against ad spend only — it doesn't account for product cost, fulfillment, or other expenses, so a high ROAS doesn't always mean a profitable campaign after all costs.

Use this tool for quick campaign-level ROAS checks, not as a substitute for full profitability analysis including product and operating costs.`,
  },

  formula: {
    formula: "ROAS = Revenue / Ad Spend; Return% = ROAS × 100",
    variables: [
      { symbol: "Revenue", meaning: "Total revenue generated by the ad campaign" },
      { symbol: "Ad Spend", meaning: "Total amount spent on the ad campaign" },
    ],
    explanation: "ROAS divides revenue generated by the amount spent on ads, expressed as a multiple (e.g. 5x) or a percentage (e.g. 500%), showing how many dollars of revenue each ad dollar produced.",
    interpretation: "For example, $5,000 in revenue from $1,000 in ad spend gives a ROAS of 5.00x (500%) — every $1 spent on ads generated $5 in revenue.",
  },

  steps: [
    "Enter the revenue generated by the ad campaign.",
    "Enter the total ad spend for the campaign.",
    "Click Calculate to run the tool.",
    "View your ROAS, return percentage and campaign profit.",
    "Compare the result against your target ROAS or break-even ROAS.",
    "Copy the summary if you need to save or share it.",
  ],

  examples: [
    { inputs: "Revenue: $5,000, Ad Spend: $1,000", result: "ROAS: 5.00x, Return: 500%, Profit: $4,000.00", explanation: "A strong ROAS where every ad dollar returned $5 in revenue." },
    { inputs: "Revenue: $1,200, Ad Spend: $1,000", result: "ROAS: 1.20x, Return: 120%, Profit: $200.00", explanation: "A modest positive ROAS — revenue only slightly exceeds ad spend." },
    { inputs: "Revenue: $800, Ad Spend: $1,000", result: "ROAS: 0.80x, Return: 80%, Profit: −$200.00", explanation: "A ROAS below 1.0x means the campaign generated less revenue than it cost, before product costs." },
    { inputs: "Revenue: $25,000, Ad Spend: $5,000", result: "ROAS: 5.00x, Return: 500%, Profit: $20,000.00", explanation: "Same 5x ROAS as the first example at a larger scale." },
  ],

  practicalUses: [
    "Evaluating whether an ad campaign is worth continuing",
    "Comparing ROAS across different ad platforms or channels",
    "Reporting campaign performance to clients or stakeholders",
    "Deciding which campaigns to scale up ad spend on",
    "Setting a minimum acceptable ROAS threshold before launch",
    "Tracking ROAS trends over the life of a campaign",
    "Comparing ROAS across different audience segments or creatives",
    "Benchmarking agency or in-house ad performance",
    "Deciding when to pause an underperforming campaign",
    "Calculating break-even ROAS needed to cover product cost",
    "Justifying ad budget increases with a clear return figure",
    "Comparing this month's ad efficiency against last month's",
  ],

  expertTips: [
    "A ROAS of 1.0x only means the campaign broke even on revenue — it likely lost money once product cost is included.",
    "Calculate your break-even ROAS (based on your profit margin) before judging whether a ROAS is 'good'.",
    "Compare ROAS across similar campaign types — awareness campaigns naturally have lower ROAS than retargeting campaigns.",
    "Track ROAS trends over time, not a single day, since ad performance fluctuates daily.",
    "High ROAS at low ad spend doesn't always scale — test increased budgets before assuming ROAS holds.",
    "Different platforms report ROAS differently (view-through vs click-through) — compare like for like.",
    "Combine ROAS with ROI when product cost is significant, for a true profitability picture.",
    "Segment ROAS by new vs returning customers — retargeting campaigns will structurally show higher ROAS than cold prospecting.",
    "Watch for diminishing ROAS as you increase budget on a single audience — it often signals audience saturation.",
  ],

  commonMistakes: [
    { mistake: "Treating ROAS 1.0x as profitable", fix: "ROAS 1.0x only breaks even on ad spend — factor in product cost to find your true break-even ROAS." },
    { mistake: "Confusing ROAS with ROI", fix: "ROAS compares revenue to ad spend only; ROI factors in product cost and other expenses for true profitability." },
    { mistake: "Judging a campaign from a single day's ROAS", fix: "Look at ROAS trends over the campaign's full duration, since daily performance can fluctuate significantly." },
    { mistake: "Comparing ROAS across very different campaign objectives", fix: "Compare ROAS only within similar campaign types, like retargeting vs retargeting, not awareness vs retargeting." },
    { mistake: "Ignoring attribution window differences when comparing platforms", fix: "Check each platform's attribution window settings before comparing ROAS figures side by side." },
    { mistake: "Scaling budget aggressively right after seeing a high ROAS", fix: "Increase spend gradually and monitor ROAS as you scale — performance rarely holds perfectly linear at higher budgets." },
  ],

  faq: [
    { q: "What is ROAS?", a: "ROAS (Return on Ad Spend) measures how much revenue is generated for every dollar spent on advertising, calculated as revenue divided by ad spend." },
    { q: "What is a good ROAS?", a: "It depends on your profit margin and industry, but many advertisers target at least 3x to 4x ROAS to remain profitable after product and operating costs." },
    { q: "How do you calculate ROAS?", a: "Divide total revenue generated by the ad campaign by the total ad spend. For example, $5,000 revenue divided by $1,000 ad spend equals a ROAS of 5.00x." },
    { q: "What is the difference between ROAS and ROI?", a: "ROAS compares revenue to ad spend only, while ROI (Return on Investment) factors in product cost and other expenses to measure true overall profitability." },
    { q: "What does a ROAS of 1.0x mean?", a: "A ROAS of 1.0x means the campaign generated exactly as much revenue as it cost in ad spend — it breaks even on ad cost but likely loses money once product cost is included." },
    { q: "What is break-even ROAS?", a: "Break-even ROAS is the minimum ROAS needed to cover both ad spend and product cost, calculated as 1 divided by your profit margin percentage." },
    { q: "How is ROAS different across platforms like Google and Meta?", a: "Each platform may use different attribution windows and models to calculate reported ROAS, so figures aren't always directly comparable without checking settings." },
    { q: "Can ROAS be negative?", a: "ROAS itself (revenue divided by spend) is never negative, but resulting profit can be negative if ad spend exceeds revenue generated." },
    { q: "What ROAS should I target for an e-commerce store?", a: "Many e-commerce businesses target 3x to 5x ROAS, but the right target depends on your product margin — lower-margin products need a higher ROAS to be profitable." },
    { q: "How often should I check my campaign's ROAS?", a: "Daily monitoring helps catch issues early, but judge overall performance using trends over at least a week to smooth out daily fluctuations." },
    { q: "What's the difference between ROAS and MER?", a: "ROAS typically measures a single campaign or channel's efficiency, while MER (Marketing Efficiency Ratio) measures total revenue against total marketing spend across all channels combined." },
    { q: "Why does my ROAS drop as I increase ad spend?", a: "Scaling budget often means reaching colder or less-targeted audiences, which typically convert at a lower rate than your initial, most-responsive audience segment." },
    { q: "Is ROAS more important than total profit?", a: "Not necessarily — a lower ROAS at much higher spend can generate more total profit than a higher ROAS at low spend, so both metrics matter together." },
    { q: "How do I calculate ROAS for multiple campaigns combined?", a: "Sum total revenue across all campaigns and divide by total combined ad spend to get a blended ROAS figure." },
    { q: "What counts as 'revenue' in a ROAS calculation?", a: "Revenue should reflect actual attributed sales from the campaign, ideally net of refunds, to avoid inflating the reported ROAS." },
    { q: "Should I include tax or shipping in ROAS revenue?", a: "Most advertisers use gross product revenue (before tax and shipping) for consistency with how ad platforms typically report conversion value." },
  ],

  relatedCalculators: ["ROI Calculator", "Profit Margin Calculator", "Customer Acquisition Cost Calculator", "Customer Lifetime Value Calculator", "Markup Calculator"],

  structuredData: ["FAQPage", "WebPage", "BreadcrumbList", "SoftwareApplication"],

  headingStructure: {
    h1: "ROAS Calculator",
    h2: ["About", "Formula", "How to Use", "Examples", "Tips", "Common Mistakes", "FAQ", "Related Calculators"],
  },
};